name: base_classes
description: It includes set of all base classes along with Utils
version: 1.0.0
author: Shubham Singhal <shubhamanonymous@gmail.com>
homepage: https://github.com/shubhamsinghan06/base_classes.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  cached_network_image: ^2.3.3
  intl: ^0.16.0
  shared_preferences: ^0.5.12
  synchronized: ^2.2.0+2
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
