name: base_classes
description: It includes set of all base classes along with Utils like Scaffold,Button,Text,TextForm Field, CustomTextForm Appbar,Constant.
version: 3.1.1
author: Shubham Singhal <shubhamanonymous@gmail.com>
homepage: https://github.com/shubhamsinghal06/base_classes.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
